# Generated by Django 5.2.10 on 2026-01-11 09:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('fuel_type', models.CharField(choices=[('AI-92', 'АИ-92'), ('AI-95', 'АИ-95'), ('AI-98', 'АИ-98'), ('DIESEL', 'Дизель'), ('GAS', 'Газ')], max_length=10, verbose_name='Тип топлива')),
                ('engine_volume', models.FloatField(verbose_name='Объем двигателя (л)')),
                ('average_consumption', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Средний расход (л/100км)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('AI-92', 'АИ-92'), ('AI-95', 'АИ-95'), ('AI-98', 'АИ-98'), ('DIESEL', 'Дизель'), ('GAS', 'Газ')], max_length=10, verbose_name='Тип топлива')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Средняя цена (руб)')),
                ('region', models.CharField(default='Москва', max_length=100, verbose_name='Регион')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('source', models.CharField(default='API', max_length=50, verbose_name='Источник')),
            ],
            options={
                'ordering': ['fuel_type'],
                'unique_together': {('fuel_type', 'region')},
            },
        ),
        migrations.CreateModel(
            name='Refuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата заправки')),
                ('odometer', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пробег (км)')),
                ('volume', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Объем (л)')),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за литр (руб)')),
                ('total_cost', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Общая стоимость (руб)')),
                ('full_tank', models.BooleanField(default=True, verbose_name='Полный бак')),
                ('station_name', models.CharField(blank=True, max_length=100, verbose_name='Название АЗС')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refuels', to='tracker.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refuels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
