# Generated by Django 5.2.10 on 2026-01-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refuel',
            name='price_per_liter',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за литр'),
        ),
        migrations.AlterField(
            model_name='refuel',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Итоговая стоимость'),
        ),
        migrations.AlterField(
            model_name='refuel',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Объем'),
        ),
    ]
